apiVersion: v1
kind: Service
metadata:
  labels:
    app: paytm-microservice
  name: paytm-microservice
  namespace: default
spec:  
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: paytm-microservice
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
