bootstrap-server: localhost:9092      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
 circuitbreaker :
  configs:
   shared :
    register-health-indicator : true
    sliding-window-size : 5
#    failure-rate-threshold=40
#    slow-call-rate-threshold=40
#    permitted-number-of-calls-in-half-open-state=1
#    max-wait-duration-in-half-open-state=10s
#    wait-duration-in-open-state=10s
#    slow-call-duration-threshold=2s
#    writable-stack-trace-enabled=true
#    automatic-transition-from-open-to-half-open-enabled=true
    

#resilience4j.circuitbreaker.configs.shared.sliding-window-type=count-based
#resilience4j.circuitbreaker.configs.shared.sliding-window-size=5
#resilience4j.circuitbreaker.configs.shared.failure-rate-threshold=40
#resilience4j.circuitbreaker.configs.shared.slow-call-rate-threshold=40
#resilience4j.circuitbreaker.configs.shared.permitted-number-of-calls-in-half-open-state=1
#resilience4j.circuitbreaker.configs.shared.max-wait-duration-in-half-open-state=10s
#resilience4j.circuitbreaker.configs.shared.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.configs.shared.slow-call-duration-threshold=2s
#resilience4j.circuitbreaker.configs.shared.writable-stack-trace-enabled=true
#resilience4j.circuitbreaker.configs.shared.automatic-transition-from-open-to-half-open-enabled=true
#
#resilience4j.circuitbreaker.instances.example.base-config=shared